{{- if (include "webhook.enabled" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trow.fullname" . }}-webhooks
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook
      name: https-webhook
    {{- if semverCompare ">=1.20" .Capabilities.KubeVersion.Version }}
      appProtocol: https
    {{- end }}
  selector:
    {{- include "webhook.selectorLabels" . | nindent 4 }}
{{- end }}
