{{- if and (include "webhook.enabled" .) .Values.webhooks.tls.certmanager.enabled }}
{{- include "webhook.validateTlsGenValues" . -}}
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "trow.fullname" . }}-cm-admission-self-signed-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "trow.fullname" . }}-cm-admission-root-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "trow.fullname" . }}-cm-admission-root-cert
  duration: {{ .Values.webhooks.tls.certmanager.rootCert.duration | default "43800h0m0s" | quote }}
  issuerRef:
    name: {{ include "trow.fullname" . }}-cm-admission-self-signed-issuer
  commonName: "ca.webhook.trow"
  isCA: true
  subject:
    organizations:
      - trow-registry
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "trow.fullname" . }}-cm-admission-root-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ include "trow.fullname" . }}-cm-admission-root-cert
---
# generate a server certificate for the apiservices to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "trow.fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "trow.fullname" . }}-cm-admission
  duration: {{ .Values.webhooks.tls.certmanager.admissionCert.duration | default "8760h0m0s" | quote }}
  issuerRef:
    {{- if .Values.webhooks.tls.certmanager.issuerRef }}
    {{- toYaml .Values.webhooks.tls.certmanager.issuerRef | nindent 4 }}
    {{- else }}
    name: {{ include "trow.fullname" . }}-cm-admission-root-issuer
    {{- end }}
  dnsNames:
    - {{ include "trow.fullname" . }}-admission
    - {{ include "trow.fullname" . }}-admission.{{ .Release.Namespace }}
    - {{ include "trow.fullname" . }}-admission.{{ .Release.Namespace }}.svc
  subject:
    organizations:
      - trow-registry
{{- end -}}
