{{ if .Values.trow.validationWebhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "trow.fullname" . }}-validation
  labels:
    {{- include "trow.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
  annotations:
  {{- if .Values.webhooks.tls.certmanager.enabled }}
    certmanager.k8s.io/inject-ca-from: {{ printf "%s/%s-admission" (.Release.Namespace) (include "trow.fullname" .) | quote }}
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-admission" (.Release.Namespace) (include "trow.fullname" .) | quote }}
  {{- end }}
webhooks:
  - name: validate.trow.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    {{ if .Values.webhooks.namespaceSelector }}
    namespaceSelector:
      {{- toYaml .Values.webhooks.namespaceSelector | toYaml | indent 6 }}
    {{- end }}
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    # Patched by job-patchWebhook.yaml
    # At first deploy we have to set to "Ignore" otherwise Trow fails to deploy
    # because the Trow webhook doesn't exist yet :/
    failurePolicy: Ignore
    clientConfig:
      service:
        name: {{ include "trow.fullname" . }}-admission
        path: "/validate-image"
        namespace: {{ .Release.Namespace }}
{{ end }}
