{{ if .Values.trow.validation.enableWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "trow.fullname" . }}-validation
  labels:
    {{- include "trow.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
webhooks:
  - name: validate.trow.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    # Patched by job-patchWebhook.yaml
    # At first deploy we have to set to "Ignore" otherwise Trow fails to deploy
    # because the Trow webhook doesn;t exist yet :/
    failurePolicy: Ignore
    clientConfig:
      service:
        name: {{ include "trow.fullname" . }}-admission
        path: "/validate-image"
        namespace: {{ .Release.Namespace }}
{{ end }}
