//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "manifest")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub manifest: Json,
    // pub artifact_type: String,
    // pub media_type: Option<String>,
    // pub annotations: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::manifest_blob_association::Entity")]
    ManifestBlobAssociation,
    #[sea_orm(has_many = "super::tag::Entity")]
    Tag,
}

impl Related<super::manifest_blob_association::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ManifestBlobAssociation.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
