//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "manifest_blob_association")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub manifest_digest: String,
    #[sea_orm(primary_key)]
    pub blob_digest: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::blob::Entity",
        from = "Column::BlobDigest",
        to = "super::blob::Column::Digest",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Blob,
    #[sea_orm(
        belongs_to = "super::manifest::Entity",
        from = "Column::ManifestDigest",
        to = "super::manifest::Column::Digest",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Manifest,
}

impl Related<super::blob::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Blob.def()
    }
}

impl Related<super::manifest::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Manifest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
