{{- if include "trow.hasConfigFile" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trow.fullname" . }}-cfg
  labels:
    {{- include "trow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: {{ include "trow.config" . | b64enc }}
{{- end }}
