apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: trow.kube-public
spec:
  groups:
  - system:authenticated
  request: $(cat server.csr | base64 | tr -d '\n')
  signerName: kubernetes.io/kubelet-serving
  usages:
  - digital signature
  - key encipherment
  - server auth
