#Not a big fan of using nightly, but such is our lot currently
FROM rust:latest as builder

RUN rustup update nightly && rustup default nightly;
RUN apt-get update && apt-get install -y cmake golang unzip
#Add checksum or GPG checking
RUN cd /usr/local && curl -o protoc.zip -sSL https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip && unzip protoc.zip

WORKDIR /usr/src/trow

#First get just the deps
COPY Cargo.toml .
COPY Cargo.lock .

RUN mkdir src/
RUN echo "fn main() {}" > src/main.rs

# trow-server
COPY lib/server/Cargo.toml lib/server/
RUN mkdir -p lib/server/src
RUN touch lib/server/src/lib.rs

# trow-protobuf
COPY lib/protobuf/Cargo.toml lib/protobuf/
RUN echo "fn main() {}" > lib/protobuf/build.rs
RUN mkdir -p lib/protobuf/src
RUN touch lib/protobuf/src/lib.rs

RUN cargo build # should cache all build deps
RUN cargo test --no-run

COPY lib lib
COPY src src
COPY tests tests
RUN mkdir certs 
COPY install/self-cert/make-certs.sh certs/
COPY install/self-cert/in.req certs/
RUN cd certs && ./make-certs.sh
RUN cargo test
