# syntax = docker/dockerfile:1

#Not a big fan of using nightly, but such is our lot currently
FROM rust:latest as builder

RUN rustup component add rustfmt
RUN apt-get update && apt-get install -y unzip

WORKDIR /usr/src/trow

#First get just the deps
COPY Cargo.toml .
COPY Cargo.lock .

COPY src src
COPY trow-server trow-server
COPY trow-protobuf trow-protobuf
COPY tests tests

RUN mkdir certs
COPY quick-install/self-cert/make-certs.sh certs/
COPY quick-install/self-cert/in.req certs/
RUN cd certs && ./make-certs.sh

RUN --mount=type=cache,target=./target \
    cargo test --workspace
